### ISSUE TITLE
8. Map erstellen

### ISSUE THREAD

**Issue by kludikovsky** [florianisystem/florianisystem#13]
Map Einbetten funktioniert nicht

**Comment by ximex** [comment]
URL: `https://helfer.ff-leobersdorf.at/map`
Optional mit parametern: `https://helfer.ff-leobersdorf.at/map?x=<lng>&y=<lat>&z=<zoom>&json=<geojson_base64>`

## Params (alle optional)
- `x`: Longitude
- `y`: Latitude
- `z`: Zoom
- `json`: "Geojson"

## Geojson
Kann man sich einfach hier erstellen: https://geojson.io/
- JSON daten minifien (Leerzeichen entfernen, Koordinaten Genauigkeit verringern,...)
- JSON mit `base64` encodieren
- Ergebnis als query param `json` anhängen

Optional kann als Attribute `name` gesetzt werden wodurch es ein Popup bei Klick gibt.
Bei setzen von `color` kann die Farbe geändert werden

**Comment by kludikovsky** [comment]
Nö, funktioniert nicht!


![Image](https://user-images.githubusercontent.com/6077916/230719962-15c1e2f9-f1f1-4fbc-88a0-d2b41fccb4bb.png)

**Comment by kludikovsky** [comment]
OK, jetzt funkts!

**Comment by ximex** [comment]
ja ich hab die domain korrigiert
