### ISSUE TITLE
9. Wenn wir DECT nicht haben, sollen wir das nicht unterdrücken?

### ISSUE THREAD

**Issue by kludikovsky** [florianisystem/florianisystem#18]
![Image](https://user-images.githubusercontent.com/6077916/230620161-83b4472e-577d-412c-afe6-d319ddcbec40.png)

**Comment by ximex** [comment]
DECT selber ist deaktiviert und DECT wurde schon in den übersetzungen zu Telefon geändert. müsste man durchtesten ob die validierung kein problem ist
