### ISSUE TITLE
15. WIR BRAUCHEN AUCH EINE ABLAUFBESCHREIBUNG!!!!

### ISSUE THREAD

**Issue by kludikovsky** [florianisystem/florianisystem#22]
Darin muss stehen WAS ind WELCHER Reihenfolge, sinnvoll angelegt werden muss. Wie die zusammenhänge sind..
Also zB

1. Räume (= Lokationen => ev. auch Umbennen)
2. Schichttypen
3. Helfertypen
4. Schichten

Ev. mit einem (vereinfachten) Realtionenmodell.

**Comment by ximex** [comment]
@kludikovsky arbeitest du nicht daran mit der dokumentation?

**Comment by kludikovsky** [comment]
Ist eh mir zugeordnet!

**Comment by ximex** [comment]
@kludikovsky kann man schließen oder?
