### ISSUE TITLE
33. Einstellung "ENABLE_GOODY" auf false setzen weil goodys sind eigentlich vouchers fürs nächste event, in diesem Fall der Satz bei der Registrierung "Um Voucher zu erhalten, stimme zu, dass Nick, E-Mail-Adresse, geleistete Arbeit und Shirtgröße bis zum nächsten gleichartigen Event gespeichert werden."

### ISSUE THREAD

**Issue by kludikovsky** [florianisystem/florianisystem#29]
![Image](https://user-images.githubusercontent.com/6077916/230622772-021842ac-93eb-4dd0-a692-5af781dc5b21.png)

Ich finde halt den Satz bei der Registrierung was von "Vouchers" zu erzählen für das nächste Feuerwehrfest, der wird der FF sicher ned passen. Es geht halt um die die T-Shirt Funktion, dafür muss  Goodys auf tshirt gesetzt werden, dann taucht aber der satz auf

**Comment by ximex** [comment]
wird jetzt nicht mehr angezeigt. `GOODIE_TYPE="tshirt"` muss aber weiterhin gesetzt sein
