### ISSUE TITLE
39. Gruppenrechte: Wir sollten überlegen ob wir die Gruppenfunktionen näher an den FF-Sprachgebrauch anpassen sollten . Wie viel Aufwand wäre das?

### ISSUE THREAD

**Issue by kludikovsky** [florianisystem/florianisystem#34]

**Comment by theskystalker** [comment]
Diese Werte/Namen stehen in der DB und können auch nur dort gändert werden. Man könnte ein weiteres Migration Script machen, oder wir schaffen beim Deployment einen zugang für solche Dinge, aka Phpmyadmin oder so
