### ISSUE TITLE
Assign to Organization

### ISSUE THREAD

**Issue by theskystalker** [florianisystem/florianisystem#50]

**Comment by theskystalker** [comment]
Pull Request eingereicht https://github.com/florianisystem/florianisystem/pull/48

**Comment by ximex** [comment]
deployed on dev

**Comment by kludikovsky** [comment]
In der Helferliste kann die Zuordnung noch nicht gemacht werden.

**Comment by theskystalker** [comment]
danke für den Vorschlag ich mach gern ein neues Issue auf, ist aber eine andere Baustelle, hier geht es um die Möglichkeit das ein neuer Benutzer bei der Registrierung bereits seine Organisation auswählen kann
