### ISSUE TITLE
Text: Benötigte Helfer -> Aufgaben

### ISSUE THREAD

**Issue by theskystalker** [florianisystem/florianisystem#61]
https://florianisystem.aws.ludikovsky.name/admin/rooms/edit/3

Beim bearbeiten der Orte steht dort "Benötigte Helfer"

![Image](https://user-images.githubusercontent.com/6077916/231757900-cabe01db-37a6-4dd5-af5a-1b41e238a432.png)

Da haben wir ein bischen das Problem das es einmal Helfer - einmal Aufgabe heißt

Vl. kann man da den Test so schreiben "Benötigte Helfer für Aufgaben"

Es trifft zwar nur den/die Admins. Ichbin geade darüber gestolpert weil ich die Helfertypen gescuht ahbe die ja jetzt  Aufgaben heißen. (Von mir selbst vorgeschlagen)

**Comment by kludikovsky** [comment]
OK, dann lassens wir.
